cat AdresaSidlo.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > AdresaSidlo.txt
cat AdresaTrvaleBydliste.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > AdresaTrvaleBydliste.txt
cat ciselnikCinnostTypCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikCinnostTypCiselnikv01.txt
cat ciselnikCinnostTypvCEDR01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikCinnostTypvCEDR01.txt
cat ciselnikDotacePoskytovatelv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikDotacePoskytovatelv01.txt
cat ciselnikDotaceTitulCiselnikAxisDotaceTitulKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikDotaceTitulCiselnikAxisDotaceTitulKodv01.txt
cat ciselnikDotaceTitulCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikDotaceTitulCiselnikv01.txt
cat ciselnikDotaceTitulParagrafv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikDotaceTitulParagrafv01.txt
cat ciselnikDotaceTitulPolozkav01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikDotaceTitulPolozkav01.txt
cat ciselnikDotaceTitulUkazatelv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikDotaceTitulUkazatelv01.txt
cat ciselnikDotaceTitulv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikDotaceTitulv01.txt
cat ciselnikFinancniProstredekCleneniCiselnikAxisFinancniProstredekCleneniKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikFinancniProstredekCleneniCiselnikAxisFinancniProstredekCleneniKodv01.txt
cat ciselnikFinancniProstredekCleneniCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikFinancniProstredekCleneniCiselnikv01.txt
cat ciselnikFinancniProstredekCleneniv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikFinancniProstredekCleneniv01.txt
cat ciselnikFinancniZdrojCiselnikAxisFinancniZdrojKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikFinancniZdrojCiselnikAxisFinancniZdrojKodv01.txt
cat ciselnikFinancniZdrojCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikFinancniZdrojCiselnikv01.txt
cat ciselnikFinancniZdrojv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikFinancniZdrojv01.txt
cat ciselnikGrantoveSchemaCEDRv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikGrantoveSchemaCEDRv01.txt
cat ciselnikGrantoveSchemaCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikGrantoveSchemaCiselnikv01.txt
cat ciselnikOpatreniCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikOpatreniCiselnikv01.txt
cat ciselnikOpatrenivCEDR01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikOpatrenivCEDR01.txt
cat ciselnikOperacniProgramCEDRv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikOperacniProgramCEDRv01.txt
cat ciselnikOperacniProgramCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikOperacniProgramCiselnikv01.txt
cat ciselnikPodOpatreniCEDRv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikPodOpatreniCEDRv01.txt
cat ciselnikPodopatreniCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikPodopatreniCiselnikv01.txt
cat ciselnikPodprogramCEDRv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikPodprogramCEDRv01.txt
cat ciselnikPodprogramCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikPodprogramCiselnikv01.txt
cat ciselnikPoskytovatelDotaceCiselnikAxisDotacePoskytovatelKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikPoskytovatelDotaceCiselnikAxisDotacePoskytovatelKodv01.txt
cat ciselnikPoskytovatelDotaceCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikPoskytovatelDotaceCiselnikv01.txt
cat ciselnikPrioritaCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikPrioritaCiselnikv01.txt
cat ciselnikPrioritavCEDR01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikPrioritavCEDR01.txt
cat ciselnikProgramPodporaCEDRv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikProgramPodporaCEDRv01.txt
cat ciselnikProgramPodporaCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikProgramPodporaCiselnikv01.txt
cat ciselnikRozpoctovaSkladbaParagrafCiselnikAxisParagrafRSKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikRozpoctovaSkladbaParagrafCiselnikAxisParagrafRSKodv01.txt
cat ciselnikRozpoctovaSkladbaParagrafCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikRozpoctovaSkladbaParagrafCiselnikv01.txt
cat ciselnikRozpoctovaSkladbaParagrafv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikRozpoctovaSkladbaParagrafv01.txt
cat ciselnikRozpoctovaSkladbaPolozkaCiselnikAxisPolozkaRSKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikRozpoctovaSkladbaPolozkaCiselnikAxisPolozkaRSKodv01.txt
cat ciselnikRozpoctovaSkladbaPolozkaCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikRozpoctovaSkladbaPolozkaCiselnikv01.txt
cat ciselnikRozpoctovaSkladbaPolozkav01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikRozpoctovaSkladbaPolozkav01.txt
cat ciselnikStatniRozpocetKapitolaCiselnikAxisKapitolaKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikStatniRozpocetKapitolaCiselnikAxisKapitolaKodv01.txt
cat ciselnikStatniRozpocetKapitolaCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikStatniRozpocetKapitolaCiselnikv01.txt
cat ciselnikStatniRozpocetKapitolav01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikStatniRozpocetKapitolav01.txt
cat ciselnikStatniRozpocetUkazatelCiselnikAxisKapitolaKodUkazatelSRKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikStatniRozpocetUkazatelCiselnikAxisKapitolaKodUkazatelSRKodv01.txt
cat ciselnikStatniRozpocetUkazatelCiselnikAxixKapitolaKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikStatniRozpocetUkazatelCiselnikAxixKapitolaKodv01.txt
cat ciselnikStatniRozpocetUkazatelCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikStatniRozpocetUkazatelCiselnikv01.txt
cat ciselnikStatniRozpocetUkazatelv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikStatniRozpocetUkazatelv01.txt
cat ciselnikUcelZnakCiselnikAxisUcelZnakKodv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikUcelZnakCiselnikAxisUcelZnakKodv01.txt
cat ciselnikUcelZnakCiselnikv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikUcelZnakCiselnikv01.txt
cat ciselnikUcelZnakv01.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > ciselnikUcelZnakv01.txt
cat CizinecFO.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > CizinecFO.txt
cat CizinecFOP.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > CizinecFOP.txt
cat CizinecPO.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > CizinecPO.txt
cat Dotace.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > Dotace.txt
cat Etapa.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > Etapa.txt
cat FyzickaOsoba.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > FyzickaOsoba.txt
cat FyzickaOsobaPodnikajici.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > FyzickaOsobaPodnikajici.txt
cat PravnickaOsoba.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > PravnickaOsoba.txt
cat PrijemcePomoci.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > PrijemcePomoci.txt
cat PrijemcePomociAres.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > PrijemcePomociAres.txt
cat PrijemcePomociRob.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > PrijemcePomociRob.txt
cat Rozhodnuti.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > Rozhodnuti.txt
cat RozhodnutiSmlouva.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > RozhodnutiSmlouva.txt
cat RozpoctoveObdobi.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > RozpoctoveObdobi.txt
cat SplatkaKalendar.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > SplatkaKalendar.txt
cat UzemniRealizace.n3 | cut -d' ' -f2 | cut -d'#' -f2 | sort | uniq -c | sort -r > UzemniRealizace.txt

tail -n +1 *.txt > _freq.txt

wc -l *.n3 | sort -r > _stats.txt